# Generated by Django 2.1.7 on 2019-04-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20190401_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='research_paper',
            field=models.FileField(blank=True, upload_to='research_papers/pdf/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='research_paper_txt',
            field=models.FileField(blank=True, upload_to='research_papers/txt/'),
        ),
    ]
