# Generated by Django 2.1.7 on 2019-04-10 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20190409_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='research_paper',
            field=models.FileField(blank=True, upload_to='research_papers/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='research_paper_txt',
            field=models.FileField(blank=True, upload_to='research_papers/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='researcher',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='researchers.Researcher'),
        ),
    ]
