# Generated by Django 2.1.7 on 2019-04-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20190410_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='abstract',
            field=models.TextField(blank=True, default='abstract'),
        ),
    ]
