# Generated by Django 2.1.7 on 2019-04-10 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20190410_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='listing_rating',
        ),
    ]
