# Generated by Django 2.1.7 on 2019-04-10 01:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20190410_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='abstract',
            field=models.TextField(blank=True, default='abstract', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
