# Generated by Django 2.1.7 on 2019-04-10 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20190410_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='researcher',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='researchers.Researcher'),
        ),
    ]
